---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
    exclude_paths:
      - test/
  eslint:
    enabled: true
    channel: eslint-2
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- test/data/
